name: Build and Publish

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  build:
    uses: mikopbx/.github-workflows/.github/workflows/extension-publish.yml@master
    with:
      initial_version: "1.70"
      custom_build_steps: |
        cd $GITHUB_WORKSPACE/module
        
        # Set up Docker cache
        DOCKER_IMAGE_TAG="tg2sip-build-env:2.1"
        DOCKER_CACHE_KEY="docker-cache-$DOCKER_IMAGE_TAG"
        
        # Try to load cached image
        echo "Loading Docker cache..."
        docker load < /tmp/docker-cache.tar || true
        
        # Build the Docker environment if not in cache
        if ! docker images | grep -q $DOCKER_IMAGE_TAG; then
          echo "Cache miss. Building Docker environment..."
          docker build -t $DOCKER_IMAGE_TAG -f $GITHUB_WORKSPACE/module/td-keyboard/build-env/Dockerfile .
        
          # Save to cache
          echo "Saving Docker image to cache..."
          docker save $DOCKER_IMAGE_TAG > /tmp/docker-cache.tar
        else
          echo "Using cached Docker image"
        fi

    secrets: inherit