name: Build and Publish

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  build:
    uses: mikopbx/.github-workflows/.github/workflows/extension-publish.yml@master
    with:
      initial_version: "1.70"
      custom_build_steps: |
        cd $GITHUB_WORKSPACE/module
        
        # Build the Docker environment
        echo "Building Docker environment..."
        docker build -t build-env:2.1 -f td-keyboard/build-env/Dockerfile .
        
        # Build tg2sip
        echo "Building tg2sip..."
        (
          cd tg2sip
        
          # Create builder container
          builder=$(docker run -t -v "$(pwd)":/src -w /src -d build-env:2.1)
        
          # Build process
          docker exec "$builder" cmake -DCMAKE_BUILD_TYPE=Release .
          docker exec "$builder" cmake --build .
        
          # Cleanup container
          docker stop $builder
          docker rm $builder
        
          # Move artifacts
          if [ -f gen_db ]; then
            mv gen_db ../bin/gen_db
          else 
            echo 'Error build gen_db'
            exit 1
          fi
        
          if [ -f tg ]; then
            mv tg bin/tg2sip
          else 
            echo 'Error build tg2sip'
            exit 1
          fi
        )
        rm -rf tg2sip
        
        # Build td-keyboard
        echo "Building td-keyboard..."
        (
          cd td-keyboard/build-env
        
          # Create builder container
          builder=$(docker run -t -v "$(pwd)/..":/src -w /src -d build-env:2.1)
        
          # Build process
          docker exec "$builder" go mod tidy
          docker exec "$builder" go build -o td-keyboard --ldflags '-extldflags "-static -L/usr/local/lib"'
        
          # Cleanup container
          docker stop $builder
          docker rm $builder
        
          # Move artifacts
          if [ -f td-keyboard ]; then
            mv td-keyboard ../../bin/td-keyboard
          else 
            echo 'Error build td-keyboard'
            exit 1
          fi
        )
        rm -rf td-keyboard
    secrets: inherit